## Applicants

In [20]:
import pandas as pd

In [21]:
df_applicants = pd.read_json("../dados/raw/applicants.json").T

In [22]:
df_applicants.head()

,infos_basicas,informacoes_pessoais,informacoes_profissionais,formacao_e_idiomas,cargo_atual,cv_pt,cv_en
31000,"{'telefone_recado': '', 'telefone': '(11) 9704...",{'data_aceite': 'Cadastro anterior ao registro...,"{'titulo_profissional': '', 'area_atuacao': ''...","{'nivel_academico': '', 'nivel_ingles': '', 'n...",{},assistente administrativo\n\n\nsantosbatista\n...,
31001,"{'telefone_recado': '', 'telefone': '(11) 9372...",{'data_aceite': 'Cadastro anterior ao registro...,{'titulo_profissional': 'Analista Administrati...,{'nivel_academico': 'Ensino Superior Incomplet...,{},formação acadêmica\nensino médio (2º grau) em ...,
31002,"{'telefone_recado': '', 'telefone': '(11) 9239...",{'data_aceite': 'Cadastro anterior ao registro...,{'titulo_profissional': 'Administrativo | Fina...,{'nivel_academico': 'Ensino Superior Completo'...,{},objetivo: área administrativa | financeira\n\n...,
31003,"{'telefone_recado': '', 'telefone': '(11) 9810...",{'data_aceite': 'Cadastro anterior ao registro...,"{'titulo_profissional': 'Área administrativa',...",{'nivel_academico': 'Ensino Superior Incomplet...,{},formação\nensino médio completo\ninformática i...,
31004,"{'telefone_recado': '', 'telefone': '(11) 9251...",{'data_aceite': 'Cadastro anterior ao registro...,"{'titulo_profissional': '', 'area_atuacao': ''...","{'nivel_academico': '', 'nivel_ingles': '', 'n...",{},última atualização em 09/11/2021\n­ sp\n\nensi...,

In [23]:
df_applicants.shape

(42482, 7)

In [24]:
df_applicants.info()

<class 'pandas.core.frame.DataFrame'>
Index: 42482 entries, 31000 to 5999
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   infos_basicas              42482 non-null  object
 1   informacoes_pessoais       42482 non-null  object
 2   informacoes_profissionais  42482 non-null  object
 3   formacao_e_idiomas         42482 non-null  object
 4   cargo_atual                42482 non-null  object
 5   cv_pt                      42482 non-null  object
 6   cv_en                      42482 non-null  object
dtypes: object(7)
memory usage: 3.6+ MB

### Pre-processamento

Como JSON não é apropriado para treinamento de modelos, é realizado uma conversao para csv

In [ ]:
data = []

for key, value in df_applicants.iterrows():
    record = {
        "codigo_profissional": value["infos_basicas"]["codigo_profissional"],
        "nome": value["infos_basicas"]["nome"],
        "telefone": value["infos_basicas"]["telefone"],
        "email": value["infos_basicas"]["email"],
        "objetivo_profissional": value["infos_basicas"]["objetivo_profissional"],
        "data_criacao": value["infos_basicas"]["data_criacao"],
        "data_atualizacao": value["infos_basicas"]["data_atualizacao"],
        "telefone_celular": value["informacoes_pessoais"]["telefone_celular"],
        "data_nascimento": value["informacoes_pessoais"]["data_nascimento"],
        "formacao_academica": value["formacao_e_idiomas"]["nivel_academico"],
        "idioma_ingles": value["formacao_e_idiomas"]["nivel_ingles"],
        "idioma_espanhol": value["formacao_e_idiomas"]["nivel_espanhol"],
        "cv_pt": value["cv_pt"]
    }
    data.append(record)


df_applicants = pd.DataFrame(data)

In [26]:
df_applicants.head()

,codigo_profissional,nome,telefone,email,objetivo_profissional,data_criacao,data_atualizacao,telefone_celular,data_nascimento,formacao_academica,idioma_ingles,idioma_espanhol,cv_pt
0,31000,Carolina Aparecida,(11) 97048-2708,carolina_aparecida@gmail.com,,10-11-2021 07:29:49,10-11-2021 07:29:49,(11) 97048-2708,0000-00-00,,,,assistente administrativo\n\n\nsantosbatista\n...
1,31001,Eduardo Rios,(11) 93723-4396,eduardo_rios@hotmail.com,Analista Administrativo,10-11-2021 08:56:16,11-11-2021 11:10:31,(11) 93723-4396,28-12-1994,Ensino Superior Incompleto,Nenhum,Nenhum,formação acadêmica\nensino médio (2º grau) em ...
2,31002,Pedro Henrique Carvalho,(11) 92399-9824,pedro_henrique_carvalho@gmail.com,Administrativo | Financeiro,10-11-2021 09:01:00,10-11-2021 11:42:36,(11) 92399-9824,12-12-1988,Ensino Superior Completo,Intermediário,Básico,objetivo: área administrativa | financeira\n\n...
3,31003,Thiago Barbosa,(11) 98100-1727,thiago_barbosa@hotmail.com,Área administrativa,10-11-2021 09:08:13,10-11-2021 16:04:51,(11) 98100-1727,08-05-1992,Ensino Superior Incompleto,Nenhum,Nenhum,formação\nensino médio completo\ninformática i...
4,31004,Diogo das Neves,(11) 92517-2678,diogo_das_neves@hotmail.com,,10-11-2021 09:18:46,10-11-2021 09:22:03,(11) 92517-2678,31-12-1969,,,,última atualização em 09/11/2021\n­ sp\n\nensi...

In [36]:
df_applicants.to_csv("../dados/trusted/applicants_trusted.csv", index=False)

## Prospects

In [31]:
df_prospects = pd.read_json("../dados/raw/prospects.json").T

In [32]:
df_prospects.head()

,titulo,modalidade,prospects
4530,CONSULTOR CONTROL M,,"[{'nome': 'José Vieira', 'codigo': '25632', 's..."
4531,2021-2607395-PeopleSoft Application Engine-Dom...,,"[{'nome': 'Sra. Yasmin Fernandes', 'codigo': '..."
4532,,,[]
4533,2021-2605708-Microfocus Application Life Cycle...,,"[{'nome': 'Arthur Almeida', 'codigo': '26338',..."
4534,2021-2605711-Microfocus QTP - UFT Automation T...,,"[{'nome': 'Ana Luiza Vieira', 'codigo': '26361..."

In [ ]:
data = []

for index, row in df_prospects.iterrows():
    for prospect in row["prospects"]:
        record = {
            "titulo": row["titulo"],
            "nome": prospect["nome"],
            "codigo": prospect["codigo"],
            "situacao_candidado": prospect["situacao_candidado"],
            "data_candidatura": prospect["data_candidatura"],
            "ultima_atualizacao": prospect["ultima_atualizacao"],
            "comentario": prospect["comentario"],
            "recrutador": prospect["recrutador"]
        }
        data.append(record)
    data.append(record)


df_prospects = pd.DataFrame(data)

In [35]:
df_prospects.head()

,titulo,nome,codigo,situacao_candidado,data_candidatura,ultima_atualizacao,comentario,recrutador
0,CONSULTOR CONTROL M,José Vieira,25632,Encaminhado ao Requisitante,25-03-2021,25-03-2021,"Encaminhado para - PJ R$ 72,00/hora",Ana Lívia Moreira
1,CONSULTOR CONTROL M,Srta. Isabela Cavalcante,25529,Encaminhado ao Requisitante,22-03-2021,23-03-2021,"encaminhado para - R$ 6.000,00 – CLT Full , n...",Ana Lívia Moreira
2,CONSULTOR CONTROL M,Srta. Isabela Cavalcante,25529,Encaminhado ao Requisitante,22-03-2021,23-03-2021,"encaminhado para - R$ 6.000,00 – CLT Full , n...",Ana Lívia Moreira
3,2021-2607395-PeopleSoft Application Engine-Dom...,Sra. Yasmin Fernandes,25364,Contratado pela Decision,17-03-2021,12-04-2021,Data de Inicio: 12/04/2021,Juliana Cassiano
4,2021-2607395-PeopleSoft Application Engine-Dom...,Alexia Barbosa,25360,Encaminhado ao Requisitante,17-03-2021,17-03-2021,,Juliana Cassiano

In [37]:
df_prospects.to_csv("../dados/trusted/prospects_trusted.csv", index=False)

## Vagas

In [38]:
df_vagas = pd.read_json("../dados/raw/vagas.json").T

In [39]:
df_vagas.head()

,informacoes_basicas,perfil_vaga,beneficios
5185,"{'data_requicisao': '04-05-2021', 'limite_espe...","{'pais': 'Brasil', 'estado': 'São Paulo', 'cid...","{'valor_venda': '-', 'valor_compra_1': 'R$', '..."
5184,"{'data_requicisao': '04-05-2021', 'limite_espe...","{'pais': 'Brasil', 'estado': 'São Paulo', 'cid...","{'valor_venda': '-', 'valor_compra_1': 'R$', '..."
5183,"{'data_requicisao': '04-05-2021', 'limite_espe...","{'pais': 'Brasil', 'estado': 'São Paulo', 'cid...","{'valor_venda': '-', 'valor_compra_1': 'R$', '..."
5182,"{'data_requicisao': '04-05-2021', 'limite_espe...","{'pais': 'Brasil', 'estado': 'São Paulo', 'cid...","{'valor_venda': '- p/ mês (168h)', 'valor_comp..."
5181,"{'data_requicisao': '04-05-2021', 'limite_espe...","{'pais': 'Brasil', 'estado': 'São Paulo', 'cid...","{'valor_venda': '-', 'valor_compra_1': 'R$', '..."

In [42]:
data = []

for key, vaga in df_vagas.iterrows():

    informacoes_basicas = vaga.get("informacoes_basicas", {})
    perfil_vaga = vaga.get("perfil_vaga", {})
    beneficios = vaga.get("beneficios", {})
    
    record = {
        "id_vaga": key,
        "data_requisicao": informacoes_basicas.get("data_requicisao", ""),
        "limite_esperado_para_contratacao": informacoes_basicas.get("limite_esperado_para_contratacao", ""),
        "titulo_vaga": informacoes_basicas.get("titulo_vaga", ""),
        "vaga_sap": informacoes_basicas.get("vaga_sap", ""),
        "cliente": informacoes_basicas.get("cliente", ""),
        "solicitante_cliente": informacoes_basicas.get("solicitante_cliente", ""),
        "empresa_divisao": informacoes_basicas.get("empresa_divisao", ""),
        "requisitante": informacoes_basicas.get("requisitante", ""),
        "analista_responsavel": informacoes_basicas.get("analista_responsavel", ""),
        "tipo_contratacao": informacoes_basicas.get("tipo_contratacao", ""),
        "prazo_contratacao": informacoes_basicas.get("prazo_contratacao", ""),
        "objetivo_vaga": informacoes_basicas.get("objetivo_vaga", ""),
        "prioridade_vaga": informacoes_basicas.get("prioridade_vaga", ""),
        "origem_vaga": informacoes_basicas.get("origem_vaga", ""),
        "superior_imediato": informacoes_basicas.get("superior_imediato", ""),
        "nome": informacoes_basicas.get("nome", ""),
        "telefone": informacoes_basicas.get("telefone", ""),
        "pais": perfil_vaga.get("pais", ""),
        "estado": perfil_vaga.get("estado", ""),
        "cidade": perfil_vaga.get("cidade", ""),
        "local_trabalho": perfil_vaga.get("local_trabalho", ""),
        "vaga_especifica_para_pcd": perfil_vaga.get("vaga_especifica_para_pcd", ""),
        "faixa_etaria": perfil_vaga.get("faixa_etaria", ""),
        "nivel_profissional": perfil_vaga.get("nivel profissional", ""),
        "nivel_academico": perfil_vaga.get("nivel_academico", ""),
        "nivel_ingles": perfil_vaga.get("nivel_ingles", ""),
        "nivel_espanhol": perfil_vaga.get("nivel_espanhol", ""),
        "areas_atuacao": perfil_vaga.get("areas_atuacao", ""),
        "principais_atividades": perfil_vaga.get("principais_atividades", ""),
        "competencia_tecnicas_e_comportamentais": perfil_vaga.get("competencia_tecnicas_e_comportamentais", ""),
        "demais_observacoes": perfil_vaga.get("demais_observacoes", ""),
        "viagens_requeridas": perfil_vaga.get("viagens_requeridas", ""),
        "equipamentos_necessarios": perfil_vaga.get("equipamentos_necessarios", ""),
        "valor_venda": beneficios.get("valor_venda", ""),
        "valor_compra_1": beneficios.get("valor_compra_1", ""),
        "valor_compra_2": beneficios.get("valor_compra_2", "")
    }
    data.append(record)


df_vagas = pd.DataFrame(data)

In [43]:
df_vagas.head()

,id_vaga,data_requisicao,limite_esperado_para_contratacao,titulo_vaga,vaga_sap,cliente,solicitante_cliente,empresa_divisao,requisitante,analista_responsavel,...,nivel_espanhol,areas_atuacao,principais_atividades,competencia_tecnicas_e_comportamentais,demais_observacoes,viagens_requeridas,equipamentos_necessarios,valor_venda,valor_compra_1,valor_compra_2
0,5185,04-05-2021,00-00-0000,Operation Lead -,Não,"Morris, Moran and Dodson",Dra. Catarina Marques,Decision São Paulo,Maria Laura Nogueira,Srta. Bella Ferreira,...,Fluente,TI - Sistemas e Ferramentas-,Operations Lead\n\nRoles & Responsibilities:\n...,Required Skills:\n• Prior experience in Cloud ...,100% Remoto Período – entre 5 – 6 meses,,Nenhum -,-,R$,
1,5184,04-05-2021,00-00-0000,Consultor PP/QM Sênior,Não,"Morris, Moran and Dodson",Dra. Catarina Marques,Decision São Paulo,Maria Laura Nogueira,Yasmin da Rosa,...,Nenhum,TI - Desenvolvimento/Programação-,Consultor PP/QM Sr.\n\n• Consultor PP/QM Sênio...,• Consultor PP/QM Sênior com experiencia em pr...,• Início: Imediato • Fim: Jan/22,,Nenhum -,-,R$,
2,5183,04-05-2021,00-00-0000,ANALISTA PL/JR C/ SQL,Não,"Morris, Moran and Dodson",Dra. Catarina Marques,Decision São Paulo,Maria Laura Nogueira,Ana Albuquerque,...,Intermediário,TI - Sistemas e Ferramentas-,Descrição – Atividades:\n\no Monitoramento das...,Requisitos mandatórios:\n\no Conhecimentos Téc...,Localização: Remoto Perfil: Analista Pleno ou ...,,Nenhum -,-,R$,
3,5182,04-05-2021,18-05-2021,Technical Architect - 11894809,Não,Nelson-Page,Dr. Raul Monteiro,Decision São Paulo,Cecília Freitas,Clara Rios,...,Básico,TI - Projetos-,Descrição/Comentário: Architecture Frameworks ...,Descrição/Comentário: Architecture Frameworks ...,Budgeted Rate - indicate currency and type (ho...,Não,Notebook padrão -,- p/ mês (168h),fechado,
4,5181,04-05-2021,00-00-0000,Consultor SAP AUTHORIZATION (BCA) -Pleno / Sênior,Não,Mann and Sons,Cauê Fogaça,Decision São Paulo,Maria Laura Nogueira,Srta. Bella Ferreira,...,Nenhum,TI - SAP-,Experiência como Consultor SAP AUTHORIZATION (...,Experiência como Consultor SAP AUTHORIZATION (...,contratação CLT full pela Decision locação rem...,Sim,Nenhum -,-,R$,

In [44]:
df_vagas.to_csv("../dados/trusted/vagas_trusted.csv", index=False)